#+TITLE: saveplace-pdf-view

=saveplace-pdf-view= extends the built-in mode =save-place= by adding
support for pdf-view (see [[https://github.com/politza/pdf-tools][pdf-tools]]) and DocView buffers.  This
package will store the place (e.g. the current page and zoom) of PDF
buffers under =pdf-view-mode= or =doc-view-mode=, and revisiting those
PDF files later using the same mode will restore the saved place.

* Installation

** MELPA

If you use [[https://melpa.org/][MELPA]], run:
#+BEGIN_SRC elisp
M-x package-install saveplace-pdf-view
#+END_SRC

** Manual

Save a copy of the code locally, and add it to your =load-path=.

* Usage

Simply require the package in your init file, and make sure
=save-place= is enabled.

#+BEGIN_SRC elisp
(require 'saveplace-pdf-view)
(save-place-mode 1)
#+END_SRC

* Similar Packages

- pdf-view-restore ([[https://github.com/007kevin/pdf-view-restore][Link]]):
  - From code review (commit 5a1947c): For each PDF file you visit in
    Emacs, =pdf-view-restore= will persist the last viewed page in a
    separate file.  This file is stored relative to the PDF file
    location.
  - =saveplace-pdf-view= (this package) persists other information
    like the scale amount and scroll position in addition to the last
    viewed page of the PDF file.  It saves those information through
    =save-place=, an Emacs built-in for saving and restoring "places"
    you visit.
